### ISSUE TITLE
Created .whl file is with improper casing

### ISSUE THREAD

**Issue by blazyy** [se2p/FlaPy#3] opened 2022-09-21 01:29 UTC
While trying to build FlaPy, I came across an issue when running `poetry build`, it was not able to find the `whl` Python file. I fixed the problem by manually renaming the file from `flapy-0.2.0-py3-none-any.whl` to `FlaPy-0.2.0-py3-none-any.whl`.

**Comment by gruberma** [comment] 2022-11-13 20:01
Hi there, apologies for the very late reply, my notifications were not set up properly.

Unfortunately I couldn't reproduce the error yet.
When I build the project freshly via `poetry build`, it creates `dist/FlaPy-0.2.0.tar.gz` just as intended.
What operating system are you using?

**Comment by gruberma** [comment] 2023-02-20 12:55
@blazyy is this still an issue to you? Otherwise I would close the issue.

**Comment by gruberma** [comment] 2023-02-22 09:54
I just found out that this is an issue with the version of poetry.

version `1.1.13` creates `FlaPy-0.2.0-py3-none-any.whl`
version `1.3.1` creates `flapy-0.2.0-py3-none-any.whl`
Somewhere in between the behavior must have changed.
So an update of poetry should solve this issue.

**Closed as completed by gruberma** 2023-02-22 09:54 UTC
